== copyright-statement

=== Copyright notice

Copyright (c) {{ docyear }} SAE ITC or its licensors.

SAE ITC +
400 Commonwealth Drive +
Warrendale, PA 15096-0001 USA

E-mail: mailto:DigitalStandardsAlliance@sae-itc.org[DigitalStandardsAlliance@sae-itc.org] +
Web: https://www.sae-itc.com/programs/dsa

Published in the United States of America

Vendors own their respective copyrights wherever they are mentioned. The
information contained in this document is provided only as general information,
which may be incomplete or outdated. Users of this document are responsible for
independently verifying any and all information. Any mention of companies or
products does not imply endorsement or support of any of the mentioned
information, services, products, or providers.

== feedback-statement

=== {blank}

// [align=center]
// **SAE International Data Specification Alliance (DSA)**:
// Advancing automotive data standards and interoperability.

// (c) SAE International {{ docyear }} - All rights reserved
