== copyright-statement

// This is authorized by the PDF Association.

=== Copyright notice

Copyright (c) {{ docyear }} PDF Association

This work is licensed under the Creative Commons Attribution 4.0 International
License.

To view a copy of this license, visit
http://creativecommons.org/licenses/by/4.0/ or send a letter to Creative
Commons, PO Box 1866, Mountain View, CA 94042, USA.

PDF Association Inc. +
{blank} +
E-mail: copyright@pdfa.org +
{blank} +
Web: https://www.pdfa.org +
{blank} +
{blank}

Vendors own their respective copyrights and trademarks wherever they are
mentioned. Attention is drawn to the possibility that some of the elements of
this document may be the subject of patent rights. The PDF Association shall not
be held responsible for identifying any or all such patent rights. Users of this
document are responsible for independently verifying any and all information.
Any mention of companies or products does not imply endorsement or support of
any of the mentioned information, services, products, or providers.


== feedback-statement

=== {blank}

== legal-statement

=== {blank}

== license-statement

=== {blank}


// [align=center]
// **PDF Association**:

// (c) PDF Association {{ docyear }} - All rights reserved
