= metanorma-custom-assets
Assets with which to customise Metanorma flavours based on other flavours

image:https://img.shields.io/gem/v/metanorma.svg["Gem Version", link="https://rubygems.org/gems/metanorma-custom-assets"]
image:https://github.com/metanorma/metanorma/workflows/rake/badge.svg["Build Status", link="https://github.com/metanorma/metanorma-custom-assets/actions?workflow=rake"]
image:https://codeclimate.com/github/metanorma/metanorma/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/metanorma/metanorma-custom-assets"]
image:https://img.shields.io/github/issues-pr-raw/metanorma/metanorma.svg["Pull Requests", link="https://github.com/metanorma/metanorma-custom-assets/pulls"]
image:https://img.shields.io/github/commits-since/metanorma/metanorma/latest.svg["Commits since latest",link="https://github.com/metanorma/metanorma-custom-assets/releases"]

== Usage
[source,console]
----
require "metanorma-custom-assets"

c = Metanorma::CustomAssets.new(:icc)
c.process_input_adoc_hdr(attributes, options)
----

The function `process_input_doc_hdr` rewrites the document attributes of a document (given as an array of docuemnt attribute lines
from the document header), and the options hash passed to `Metanorma::Compile.process_input_adoc()`, to conform with the expectations
of the flavour named in the class initialisation. Any document attributes are inserted before the current attributes of the document,
so that the document can override them if necessary with its own values.

The module method `aliases` maps the flavour to predefined Metanorma flavours, and indicates that the nominated flavour is a customisation
of that flavour.


