== copyright-statement

// This is approved by ICC at metanorma/metanorma-taste#16
// Modified from mn-samples-icc's copyright-2004.adoc with the removal of the
// phrase 'modify, '.

=== Copyright notice

Copyright (c) {{ docyear }} International Color Consortium (R)

Permission is hereby granted, free of charge, to any person obtaining a copy of
this Specification (the "Specification") to exploit the Specification without
restriction including, without limitation, the rights to use, copy, merge,
publish, distribute, and/or sublicense, copies of the Specification, and to
permit persons to whom the Specification is furnished to do so, subject to the
following conditions:

Elements of this Specification may be the subject of intellectual property
rights of third parties throughout the world including, without limitation,
patents, patent application, utility, models, copyrights, trade secrets or other
proprietary rights ("Third Party IP Rights"). Although no Third Party IP Rights
have been brought to the attention of the International Color Consortium (the
"ICC") by its members, or as a result of the publication of this Specification
in certain trade journals, the ICC has not conducted any independent
investigation regarding the existence of Third Party IP Rights. The ICC shall
not be held responsible for identifying Third Party IP Rights that may be
implicated by the practice of this Specification or the permissions granted
above, for conducting inquiries into the applicability, existence, validity, or
scope of any Third Party IP Rights that are brought to the ICC's attention, or
for obtaining licensing assurances with respect to any Third Party IP Rights.

THE SPECIFICATION IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS,
IMPLIED, OR OTHERWISE INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NONINFRINGEMENT, QUIET
ENJOYMENT, SYSTEM INTEGRATION, AND DATA ACCURACY. IN NO EVENT SHALL THE ICC BE
LIABLE FOR ANY CLAIM, DAMAGES, LOSSES, EXPENSES OR OTHER LIABILITY, WHETHER IN
AN ACTION OF CONTRACT, TORT OR OTHERWISE, CAUSED BY, ARISING OR RESULTING FROM,
OR THAT RELATE TO THE SPECIFICATION OR THE PRACTICE OR OTHER EXPLOITATION OF THE
SPECIFICATION. FURTHER, YOU HEREBY AGREE TO DEFEND, INDEMNIFY AND HOLD HARMLESS
THE ICC, AND ITS DIRECTORS AND EMPLOYEES, FROM AND AGAINST ANY AND ALL THIRD
PARTY CLAIMS, ACTIONS SUITS, DAMAGES, LOSSES, COSTS, EXPENSES, OR OTHER
LIABILITIES (INCLUDING REASONABLE ATTORNEY'S FEES AND EXPENSES) THAT WERE CAUSED
BY, ARISE OR RESULT FROM, OR RELATE TO, YOUR PRACTICE OR OTHER EXPLOITATION OF
THE SPECIFICATION (INCLUDING, WITHOUT LIMITATION, CLAIMS OF INFRINGEMENT).

The above copyright notice, permission, and conditions and disclaimers shall be
included in all copies of any material portion of the Specification. Except as
contained in this statement, the name "International Color Consortium" shall not
be used in advertising or otherwise to promote the use or other dealings in this
Specification without prior written authorization from the ICC.

=== Licenses and trademarks

International Color Consortium and the ICC logo are registered trademarks of the
International Color Consortium.

Rather than put a trademark symbol in every occurrence of other trademarked
names, we state that we are using the names only in an editorial fashion, and to
the benefit of the trademark owner, with no intention of infringement of the
trademark.

=== For additional information on the ICC

Visit the ICC Web site: http://www.color.org


== feedback-statement

=== {blank}

// [align=center]
// **International Color Consortium**:
// Standardizing [css color:blue]#color# fidelity since 1993.

// (c) ICC {{ docyear }} - All rights reserved
